var R=require("../../../../chunks/ssr/[turbopack]_runtime.js")("server/app/stories/[storySlug]/[chapterSlug]/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0hjak81._.js")
R.c("server/chunks/ssr/0q75_next_dist_esm_build_templates_app-page_105etij.js")
R.c("server/chunks/ssr/[root-of-the-server]__0q7s_oz._.js")
R.c("server/chunks/ssr/0q75_next_dist_0vi07~x._.js")
R.c("server/chunks/ssr/0q75_next_dist_01ylz7-._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0jdng7-._.js")
R.c("server/chunks/ssr/[root-of-the-server]__04vgt78._.js")
R.c("server/chunks/ssr/[root-of-the-server]__03j_4dz._.js")
R.c("server/chunks/ssr/tang-thu-ca_src_app_not-found_tsx_06bwfmv._.js")
R.c("server/chunks/ssr/0q75_next_dist_client_components_04.8ywa._.js")
R.c("server/chunks/ssr/0q75_next_dist_client_components_builtin_unauthorized_11ken72.js")
R.c("server/chunks/ssr/0q75_next_dist_client_components_builtin_global-error_0a86~ql.js")
R.c("server/chunks/ssr/07dm_next-internal_server_app_stories_[storySlug]_[chapterSlug]_page_actions_0o-vtx9.js")
R.m(22164)
module.exports=R.m(22164).exports
