var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/stories/[storySlug]/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0_1chm9._.js")
R.c("server/chunks/ssr/0q75_next_dist_esm_build_templates_app-page_0o1avxo.js")
R.c("server/chunks/ssr/0q75_next_dist_0vi07~x._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0q7s_oz._.js")
R.c("server/chunks/ssr/0q75_next_dist_01ylz7-._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0jdng7-._.js")
R.c("server/chunks/ssr/[root-of-the-server]__04vgt78._.js")
R.c("server/chunks/ssr/[root-of-the-server]__03j_4dz._.js")
R.c("server/chunks/ssr/tang-thu-ca_src_app_not-found_tsx_06bwfmv._.js")
R.c("server/chunks/ssr/0q75_next_dist_client_components_04.8ywa._.js")
R.c("server/chunks/ssr/0q75_next_dist_client_components_builtin_unauthorized_11ken72.js")
R.c("server/chunks/ssr/0q75_next_dist_client_components_builtin_global-error_0a86~ql.js")
R.c("server/chunks/ssr/tang-thu-ca__next-internal_server_app_stories_[storySlug]_page_actions_0~i__jk.js")
R.m(92308)
module.exports=R.m(92308).exports
