var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/_global-error/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0jg18.d._.js")
R.c("server/chunks/ssr/0q75_next_dist_0vi07~x._.js")
R.c("server/chunks/ssr/0q75_next_dist_esm_build_templates_app-page_0d1q5ye.js")
R.c("server/chunks/ssr/[root-of-the-server]__0jdng7-._.js")
R.c("server/chunks/ssr/[root-of-the-server]__04vgt78._.js")
R.c("server/chunks/ssr/0q75_next_dist_client_components_builtin_global-error_0a86~ql.js")
R.c("server/chunks/ssr/tang-thu-ca__next-internal_server_app__global-error_page_actions_058u-g_.js")
R.m(71649)
module.exports=R.m(71649).exports
